# Rustfmt configuration for gun.rs

# Formatting options
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Import formatting (stable options only)
reorder_imports = true

# Other options
remove_nested_parens = true
use_field_init_shorthand = true

